Cucumber steps update
strongqa/howitzer_example_cucumber pull request #9
Opened 2017-11-20 14:28 UTC by Lec1k

2017-11-20 15:29 UTC, romikoops commented on features/step_definitions/account_steps.rb
> +When 'I fill form on edit account page with incorrect' do
looks like not completed step

2017-11-20 15:33 UTC, romikoops requested changes
see my comment

2017-11-20 16:09 UTC, knlynda commented on features/step_definitions/account_steps.rb
> +When 'I fill form on edit account page with incorrect' do
yes, should be something like this: `When /^I fill form on edit account page with incorrect email$/ do`

2017-11-20 16:13 UTC, knlynda commented on features/step_definitions/common_steps.rb
> +When /I click Forgot password\? link on login page/ do
can we change it to:
```ruby
When 'I click Forgot password? link on login page' do
```

2017-11-20 16:14 UTC, knlynda commented on features/step_definitions/common_steps.rb
> +When /I log out/ do
It looks like it also can be converted to
```ruby
When 'I log out' do
```

2017-11-20 16:16 UTC, knlynda approved these changes

2017-11-20 16:18 UTC, knlynda requested changes
looks good, but please try to fix the minor things in step definitions.

2017-11-28 17:23 UTC, romikoops approved these changes

2017-11-29 08:46 UTC, merged